const english_language_2021 = [ 
  {
    "exam_type": "BECE",
    "exam_year": 2021,
    "exam_session": "May/June",
    "region": "Ghana",
    "subject": "English Language",
    "syllabus_version": "2020 Syllabus",
    "questions": [
      {
        "question": "You will be ill if you ______ raw meat.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Verb Tense",
        "options": ["ate", "eat", "had eaten", "have eaten"],
        "correct_answers": ["eat"],
        "explanation": "In this conditional sentence, 'eat' is the correct choice because it uses the present tense, which is standard in the 'if' clause of a first conditional sentence to describe a likely future outcome. The structure 'if you eat raw meat, you will be ill' indicates a cause-and-effect relationship in the present or future. The other options—'ate' (past tense), 'had eaten' (past perfect), and 'have eaten' (present perfect)—do not fit the conditional structure.",
        "hint": "Focus on the verb tense used in conditional sentences to describe a possible future situation.",
        "difficulty": "Easy",
        "marks": 1,
        "media_url": "https://example.com/english/grammar_tense.jpg",
        "media_type": "image",
        "keywords": ["grammar", "verb", "tense"],
        "learning_objectives": ["Understand verb tenses", "Apply correct tense in sentences"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests basic understanding of verb tenses."
      },
      {
        "question": " ______ the challenges, we succeeded.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Prepositions",
        "options": ["As such", "However", "In spite of", "Nevertheless"],
        "correct_answers": ["In spite of"],
        "explanation": "The preposition 'In spite of' is correct because it introduces a phrase that contrasts with the main clause, indicating that success was achieved despite obstacles. The sentence 'In spite of the challenges, we succeeded' conveys this contrast clearly. The other options—'As such' (conclusion), 'However' (adverb), and 'Nevertheless' (adverb)—do not function as prepositions or fit the sentence structure.",
        "hint": "Choose a preposition that introduces a contrast to the idea of succeeding.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/prepositions.jpg",
        "media_type": "image",
        "keywords": ["grammar", "preposition", "contrast"],
        "learning_objectives": ["Identify prepositions", "Use prepositions correctly"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question assesses knowledge of prepositional phrases."
      },
      {
        "question": "My neighbour, ______ dog barks every night, has left town.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Pronouns",
        "options": ["which", "who", "who's", "whose"],
        "correct_answers": ["whose"],
        "explanation": "The pronoun 'whose' is correct because it is a possessive pronoun that refers to the neighbour and shows ownership of the dog. The sentence 'My neighbour, whose dog barks every night, has left town' correctly indicates possession. The other options—'which' (for things), 'who' (subject pronoun), and 'who's' (contraction of 'who is')—do not convey possession or fit grammatically.",
        "hint": "Select a pronoun that shows the neighbour owns the dog.",
        "difficulty": "Easy",
        "marks": 1,
        "media_url": "https://example.com/english/pronouns.jpg",
        "media_type": "image",
        "keywords": ["grammar", "pronoun", "possessive"],
        "learning_objectives": ["Understand possessive pronouns", "Apply pronouns in sentences"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests pronoun usage and possession."
      },
      {
        "question": "She does not like ______ letters.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Gerunds",
        "options": ["to be writing", "to write", "write", "writing"],
        "correct_answers": ["writing"],
        "explanation": "The verb 'like' is commonly followed by a gerund, a verb form ending in '-ing' that acts as a noun. In this sentence, 'writing' is the correct gerund, as in 'She does not like writing letters,' where 'writing' describes the activity she dislikes. The other options—'to be writing' (progressive infinitive), 'to write' (infinitive), and 'write' (base verb)—are not grammatically correct after 'like' in this context.",
        "hint": "Look for the verb form that functions as a noun after the verb 'like.'",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/gerunds.jpg",
        "media_type": "image",
        "keywords": ["gerunds", "verb forms", "grammar"],
        "learning_objectives": ["Understand the use of gerunds after certain verbs", "Identify appropriate verb forms in sentence construction"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "The question effectively tests the understanding of gerunds, but consider providing a follow-up example to reinforce the concept."
      },
      {
        "question": "It is high time we ______ the journey.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Subjunctive Mood",
        "options": ["are starting", "shall start", "start", "started"],
        "correct_answers": ["started"],
        "explanation": "The expression 'It is high time' triggers the subjunctive mood, which uses the past tense form to express urgency or necessity, regardless of actual time. 'Started' is correct, as in 'It is high time we started the journey,' indicating the action should occur soon. The other options—'are starting' (present continuous), 'shall start' (future), and 'start' (present)—do not conform to the subjunctive mood required here.",
        "hint": "Choose the verb form used in the subjunctive mood to show urgency after 'It is high time.'",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/subjunctive.jpg",
        "media_type": "image",
        "keywords": ["subjunctive mood", "verb tense", "grammar"],
        "learning_objectives": ["Understand the use of the subjunctive mood after certain expressions", "Identify correct verb forms in subjunctive constructions"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "The question effectively assesses knowledge of the subjunctive mood, but including a distractor with a similar structure could increase difficulty."
      },
      {
        "question": "My brother, together with his wife and children, ______ travelling to Salaga next weekend.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Subject-Verb Agreement",
        "options": ["are", "is", "was", "were"],
        "correct_answers": ["is"],
        "explanation": "The subject of the sentence is 'My brother,' which is singular. The phrase 'together with his wife and children' is a prepositional phrase that does not affect the subject's number. Thus, the singular verb 'is' is correct, as in 'My brother, together with his wife and children, is travelling to Salaga next weekend.' The present tense is used for the future action ('next weekend'). The other options—'are' (plural), 'was' (past singular), and 'were' (past plural)—do not match the singular subject or tense.",
        "hint": "Determine the main subject and whether it is singular or plural, ignoring any additional phrases.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/subject_verb.jpg",
        "media_type": "image",
        "keywords": ["subject-verb agreement", "singular subject", "prepositional phrase"],
        "learning_objectives": ["Understand how to identify the subject in a sentence with prepositional phrases", "Apply correct verb agreement based on the subject's number"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question effectively assesses subject-verb agreement. Consider adding a distractor with a compound subject to increase complexity."
      },
      {
        "question": "Habib goes to school ______ train.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Prepositions",
        "options": ["by", "in", "on", "with"],
        "correct_answers": ["by"],
        "explanation": "The preposition 'by' is correct when indicating the mode of transportation, as in 'Habib goes to school by train.' It specifies the means by which Habib travels. The other options—'in' (used for enclosed spaces like cars), 'on' (used for surfaces or public transport in some contexts), and 'with' (indicating accompaniment)—are not appropriate for this context.",
        "hint": "Select the preposition commonly used to describe a mode of transportation like a train.",
        "difficulty": "Easy",
        "marks": 1,
        "media_url": "https://example.com/english/prepositions_travel.jpg",
        "media_type": "image",
        "keywords": ["grammar", "preposition", "transport"],
        "learning_objectives": ["Use prepositions of means", "Identify correct prepositions"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests preposition usage for transportation."
      },
      {
        "question": "You would be hungry if you ______ to eat.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Conditional Sentences",
        "options": ["are refusing", "refuse", "refused", "were refusing"],
        "correct_answers": ["refused"],
        "explanation": "In this hypothetical conditional sentence, 'refused' is correct because it uses the past tense in the 'if' clause of a second conditional to describe an unreal or unlikely situation. The sentence 'You would be hungry if you refused to eat' implies a hypothetical scenario. The other options—'are refusing' (present continuous), 'refuse' (present), and 'were refusing' (past continuous)—do not fit the second conditional structure.",
        "hint": "Choose the past tense verb for a hypothetical situation in a conditional sentence.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/conditionals.jpg",
        "media_type": "image",
        "keywords": ["grammar", "conditional", "subjunctive"],
        "learning_objectives": ["Understand conditional sentences", "Use subjunctive mood"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question evaluates conditional sentence construction."
      },
      {
        "question": "I prefer oranges ______ mangoes.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Conjunctions",
        "options": ["on", "than", "to", "for"],
        "correct_answers": ["to"],
        "explanation": "The conjunction 'to' is correct after the verb 'prefer' when comparing two items, as in 'I prefer oranges to mangoes.' This is the standard structure for expressing preference. The other options—'on' (preposition for location), 'than' (used with comparatives), and 'for' (used for purpose or benefit)—do not fit the grammatical structure of preference expressions.",
        "hint": "Select the conjunction typically used after 'prefer' when comparing two things.",
        "difficulty": "Easy",
        "marks": 1,
        "media_url": "https://example.com/english/conjunctions.jpg",
        "media_type": "image",
        "keywords": ["grammar", "conjunction", "preference"],
        "learning_objectives": ["Use conjunctions correctly", "Understand preference expressions"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests basic conjunction usage."
      },
      {
        "question": "His aunt ______ spoke to us in Twi.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Adverbs",
        "options": ["confidently", "confident", "confidence", "confidential"],
        "correct_answers": ["confidently"],
        "explanation": "An adverb is needed to describe how the aunt spoke, and 'confidently' is correct, as in 'His aunt confidently spoke to us in Twi.' Adverbs, often ending in '-ly,' modify verbs to indicate manner. The other options—'confident' (adjective), 'confidence' (noun), and 'confidential' (adjective)—do not modify the verb 'spoke' or fit the context.",
        "hint": "Pick a word that describes the manner of speaking and modifies the verb 'spoke.'",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/adverbs.jpg",
        "media_type": "image",
        "keywords": ["adverbs", "manner", "verb modification"],
        "learning_objectives": ["Identify adverbs that describe the manner of an action", "Distinguish between adverbs and other parts of speech"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question effectively assesses advanced adverb usage. Including a distractor with a less common adverb could further test precision."
      },
      {
        "question": "She will not give us ______ more money.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Quantifiers",
        "options": ["any", "even", "much", "little"],
        "correct_answers": ["any"],
        "explanation": "In negative sentences, the quantifier 'any' is used to indicate none or zero amount, as in 'She will not give us any more money.' This fits the context of denying additional money. The other options—'even' (adverb for emphasis), 'much' (used with uncountable nouns in questions/negatives), and 'little' (indicating a small amount)—do not suit the sentence structure or meaning.",
        "hint": "Choose a quantifier that works in a negative sentence to indicate none at all.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/quantifiers.jpg",
        "media_type": "image",
        "keywords": ["grammar", "quantifier", "negation"],
        "learning_objectives": ["Understand quantifiers", "Apply quantifiers in sentences"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests quantifier usage in negative contexts."
      },
      {
        "question": "You have seen them, ______ you?",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Question Tags",
        "options": ["didn't", "hadn't", "haven't", "hadn't"],
        "correct_answers": ["haven't"],
        "explanation": "The question tag 'haven't' is correct because it matches the present perfect tense of the main clause 'You have seen them.' In question tags, the auxiliary verb and tense mirror the main clause, and since the statement is positive, the tag is negative, as in 'You have seen them, haven't you?' The other options—'didn't' (past simple) and 'hadn't' (past perfect)—do not match the tense.",
        "hint": "Ensure the question tag uses the same tense as the main verb and reverses its polarity.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/question_tags.jpg",
        "media_type": "image",
        "keywords": ["grammar", "question tag", "tense"],
        "learning_objectives": ["Use question tags", "Match tenses"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question evaluates question tag formation."
      },
      {
        "question": "Arabah could not resist ______ the food while it was still on the fire.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Gerunds",
        "options": ["by opening", "opening", "to open", "opened"],
        "correct_answers": ["opening"],
        "explanation": "The verb 'resist' is typically followed by a gerund, a verb form ending in '-ing' that functions as a noun. 'Opening' is correct, as in 'Arabah could not resist opening the food while it was still on the fire,' where 'opening' is the object of 'resist.' The other options—'by opening' (prepositional phrase), 'to open' (infinitive), and 'opened' (past tense)—are not grammatically suitable after 'resist.'",
        "hint": "Select the verb form that acts as a noun after the verb 'resist.'",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/gerunds_resist.jpg",
        "media_type": "image",
        "keywords": ["grammar", "gerund", "verb"],
        "learning_objectives": ["Identify gerunds", "Use gerunds as objects"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests gerund usage after verbs."
      },
      {
        "question": "It was done according ______ the rules.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Prepositions",
        "options": ["by", "of", "to", "with"],
        "correct_answers": ["to"],
        "explanation": "The preposition 'to' is correct after 'according,' as in 'It was done according to the rules,' meaning it followed the rules. 'According to' is a fixed phrase used to indicate conformity or reference. The other options—'by' (means or agent), 'of' (possession), and 'with' (accompaniment)—do not form a correct phrase with 'according.'",
        "hint": "Choose the preposition that pairs with 'according' to mean following or in line with.",
        "difficulty": "Easy",
        "marks": 1,
        "media_url": "https://example.com/english/prepositions_according.jpg",
        "media_type": "image",
        "keywords": ["grammar", "preposition", "according"],
        "learning_objectives": ["Use prepositions correctly", "Understand phrase structure"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question assesses preposition usage."
      },
      {
        "question": "Can I borrow your ______ hat?",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Adjective Order",
        "options": ["blue new straw", "new blue straw", "new straw blue", "straw new blue"],
        "correct_answers": ["new blue straw"],
        "explanation": "The correct answer is 'new blue straw' because English adjective order typically follows: opinion, size, age, color, material, noun. Here, 'new' (age), 'blue' (color), and 'straw' (material) are in the correct sequence, as in 'Can I borrow your new blue straw hat?' The other options violate this standard order, making them incorrect.",
        "hint": "Arrange the adjectives in the standard order: age, color, material.",
        "difficulty": "Hard",
        "marks": 1,
        "media_url": "https://example.com/english/adjective_order.jpg",
        "media_type": "image",
        "keywords": ["grammar", "adjective", "order"],
        "learning_objectives": ["Understand adjective order", "Apply adjective rules"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests adjective order rules."
      },
      {
        "question": "The porter could not <u>endure</u> his insults.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Synonyms",
        "options": ["accept", "agree", "approve", "bear"],
        "correct_answers": ["bear"],
        "explanation": "The word 'endure' means to tolerate or withstand something unpleasant, and 'bear' is its closest synonym, as in 'The porter could not bear his insults.' The other options—'accept' (receive willingly), 'agree' (concur), and 'approve' (endorse)—do not convey the same meaning of tolerating something negative.",
        "hint": "Choose a word that means to tolerate or withstand something unpleasant.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/synonyms_endure.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "synonym", "endure"],
        "learning_objectives": ["Identify synonyms", "Expand vocabulary"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests synonym recognition."
      },
      {
        "question": "Arming the police does not <u>halt</u> crime.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Synonyms",
        "options": ["avoid", "prevent", "stop", "suspend"],
        "correct_answers": ["prevent"],
        "explanation": "The word 'halt' means to bring something to a stop, often proactively, and 'prevent' is its closest synonym, as in 'Arming the police does not prevent crime.' 'Prevent' implies stopping something before it happens. The other options—'avoid' (evade), 'stop' (general cessation), and 'suspend' (pause temporarily)—are less precise in this context.",
        "hint": "Select a word that means to stop something before it occurs.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/synonyms_halt.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "synonym", "halt"],
        "learning_objectives": ["Identify synonyms", "Understand word meanings"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question assesses synonym knowledge."
      },
      {
        "question": "The <u>chosen</u> poems are very relatable.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Synonyms",
        "options": ["preferred", "selected", "prescribed", "given"],
        "correct_answers": ["selected"],
        "explanation": "The word 'chosen' refers to something picked or selected, and 'selected' is its closest synonym, as in 'The selected poems are very relatable.' The other options—'preferred' (liked more), 'prescribed' (ordered or recommended), and 'given' (provided)—do not convey the same meaning of being deliberately picked.",
        "hint": "Choose a word that means deliberately picked or chosen.",
        "difficulty": "Easy",
        "marks": 1,
        "media_url": "https://example.com/english/synonyms_chosen.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "synonym", "chosen"],
        "learning_objectives": ["Identify synonyms", "Expand vocabulary"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests basic synonym recognition."
      },
      {
        "question": "The youth should be ruled by the <u>fundamental</u> ideals of courtesy.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Synonyms",
        "options": ["essential", "known", "popular", "realistic"],
        "correct_answers": ["essential"],
        "explanation": "The word 'fundamental' refers to something basic or essential to a system, and 'essential' is its closest synonym, as in 'The youth should be ruled by the essential ideals of courtesy.' The other options—'known' (familiar), 'popular' (widely liked), and 'realistic' (practical)—do not match the meaning of 'fundamental' in this context.",
        "hint": "Select a word that means basic or necessary, like 'fundamental.'",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/synonyms_fundamental.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "synonym", "fundamental"],
        "learning_objectives": ["Identify synonyms", "Understand word meanings"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question evaluates synonym understanding."
      },
      {
        "question": "All the <u>lax</u> rules have been cancelled.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Synonyms",
        "options": ["mild", "previous", "weak", "wrong"],
        "correct_answers": ["mild"],
        "explanation": "The word 'lax' means lenient or not strict, and 'mild' is its closest synonym, as in 'All the mild rules have been cancelled.' 'Mild' conveys a similar sense of being relaxed or not severe. The other options—'previous' (earlier), 'weak' (lacking strength), and 'wrong' (incorrect)—do not align with the meaning of 'lax.'",
        "hint": "Choose a word that means lenient or not strict, like 'lax.'",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/synonyms_lax.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "synonym", "lax"],
        "learning_objectives": ["Identify synonyms", "Expand vocabulary"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests synonym recognition."
      },
      {
        "question": "The project is <u>in the pipeline</u>. This means that it is",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Idioms",
        "options": ["being dealt with", "being suspended", "no longer pursued", "stuck in the pipe"],
        "correct_answers": ["being dealt with"],
        "explanation": "The idiom 'in the pipeline' means a project is currently being processed or worked on, making 'being dealt with' the correct choice, as in 'The project is being dealt with.' The other options—'being suspended' (paused), 'no longer pursued' (abandoned), and 'stuck in the pipe' (literal misinterpretation)—do not reflect the idiom's figurative meaning.",
        "hint": "Consider what the idiom 'in the pipeline' implies about a project's progress.",
        "difficulty": "Hard",
        "marks": 1,
        "media_url": "https://example.com/english/idioms_pipeline.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "idiom", "pipeline"],
        "learning_objectives": ["Understand idioms", "Interpret figurative language"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question assesses idiom comprehension."
      },
      {
        "question": "Azara <u>burnt her fingers</u> when she took sides with her friend. This means that Azara",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Idioms",
        "options": ["got herself into trouble", "hated her friend", "showed how brave she was", "supported her friend"],
        "correct_answers": ["got herself into trouble"],
        "explanation": "The idiom 'burnt her fingers' means to suffer negative consequences from a risky action, so 'got herself into trouble' is correct, as in 'Azara got herself into trouble when she took sides with her friend.' The other options—'hated her friend' (unrelated), 'showed how brave she was' (positive connotation), and 'supported her friend' (literal action)—do not capture the idiom's meaning.",
        "hint": "Think about the consequences of a risky decision implied by 'burnt her fingers.'",
        "difficulty": "Hard",
        "marks": 1,
        "media_url": "https://example.com/english/idioms_burnt_fingers.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "idiom", "trouble"],
        "learning_objectives": ["Understand idioms", "Interpret figurative language"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests idiom interpretation."
      },
      {
        "question": "A desperate man may <u>clutch at straws</u> to save himself. This means that he may",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Idioms",
        "options": ["decide to act bravely", "seize any opportunity", "try all clever means", "use a secret strategy"],
        "correct_answers": ["seize any opportunity"],
        "explanation": "The idiom 'clutch at straws' means to desperately grasp at any possibility, no matter how unlikely, so 'seize any opportunity' is correct, as in 'A desperate man may seize any opportunity to save himself.' The other options—'decide to act bravely' (implies courage), 'try all clever means' (suggests strategy), and 'use a secret strategy' (implies hidden plans)—do not convey the desperate nature of the idiom.",
        "hint": "Consider what a desperate person might do when grasping at straws for hope.",
        "difficulty": "Hard",
        "marks": 1,
        "media_url": "https://example.com/english/idioms_clutch_straws.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "idiom", "desperation"],
        "learning_objectives": ["Understand idioms", "Interpret figurative language"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question evaluates idiom understanding."
      },
      {
        "question": "Gil <u>held her tongue</u> on sensitive political issues. This means that she",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Idioms",
        "options": ["bit her tongue", "kept silent", "maintained her stand", "refused to laugh"],
        "correct_answers": ["kept silent"],
        "explanation": "The idiom 'held her tongue' means to refrain from speaking, so 'kept silent' is correct, as in 'Gil kept silent on sensitive political issues.' The other options—'bit her tongue' (literal or different idiom), 'maintained her stand' (implies firmness), and 'refused to laugh' (unrelated)—do not reflect the idiom's meaning of staying quiet.",
        "hint": "Think about what it means to avoid speaking on a sensitive topic.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/idioms_held_tongue.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "idiom", "silence"],
        "learning_objectives": ["Understand idioms", "Interpret figurative language"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests idiom comprehension."
      },
      {
        "question": "Ammon has always kept his enemies <u>at arm's length</u>. This means that he",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Idioms",
        "options": ["abused them", "shunned them", "threatened them", "trusted them"],
        "correct_answers": ["shunned them"],
        "explanation": "The idiom 'at arm's length' means to keep someone at a distance, avoiding close involvement, so 'shunned them' is correct, as in 'Ammon has always shunned his enemies.' The other options—'abused them' (hostile action), 'threatened them' (aggressive intent), and 'trusted them' (opposite meaning)—do not align with the idiom's sense of avoidance.",
        "hint": "Consider what it means to keep enemies distant or uninvolved.",
        "difficulty": "Hard",
        "marks": 1,
        "media_url": "https://example.com/english/idioms_arm_length.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "idiom", "distance"],
        "learning_objectives": ["Understand idioms", "Interpret figurative language"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question assesses idiom interpretation."
      },
      {
        "question": "Abeiku feels <u>unsafe</u> in his house.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Antonyms",
        "options": ["afraid", "rejected", "secure", "unhappy"],
        "correct_answers": ["secure"],
        "explanation": "The word 'unsafe' means not safe, and its antonym is 'secure,' meaning safe or protected, as in 'Abeiku feels secure in his house.' The other options—'afraid' (fearful), 'rejected' (dismissed), and 'unhappy' (sad)—do not directly oppose the meaning of 'unsafe.'",
        "hint": "Choose the word that means the opposite of 'unsafe' in terms of safety.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/antonyms_unsafe.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "antonym", "safe"],
        "learning_objectives": ["Identify antonyms", "Expand vocabulary"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests antonym recognition."
      },
      {
        "question": "That shop has been <u>temporarily</u> closed down.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Antonyms",
        "options": ["constantly", "deliberately", "legally", "permanently"],
        "correct_answers": ["permanently"],
        "explanation": "The word 'temporarily' means for a limited time, and its antonym is 'permanently,' meaning for an indefinite or long time, as in 'That shop has been permanently closed down.' The other options—'constantly' (continuously), 'deliberately' (intentionally), and 'legally' (lawfully)—do not oppose the meaning of 'temporarily.'",
        "hint": "Select the word that means the opposite of closing for a short time.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/antonyms_temporarily.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "antonym", "time"],
        "learning_objectives": ["Identify antonyms", "Understand word opposites"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question evaluates antonym understanding."
      },
      {
        "question": "The audience laughed at his <u>funny</u> stories.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Antonyms",
        "options": ["cheerful", "humourless", "familiar", "peculiar"],
        "correct_answers": ["humourless"],
        "explanation": "The word 'funny' means humorous, and its antonym is 'humourless,' meaning lacking humor, as in 'The audience did not laugh at his humourless stories.' The other options—'cheerful' (happy), 'familiar' (known), and 'peculiar' (strange)—do not directly oppose the meaning of 'funny.'",
        "hint": "Choose the word that means the opposite of humorous or amusing.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/antonyms_funny.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "antonym", "humor"],
        "learning_objectives": ["Identify antonyms", "Expand vocabulary"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests antonym recognition."
      },
      {
        "question": "The prefect <u>rebuked</u> the student for his rude behavior.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Antonyms",
        "options": ["defended", "justified", "pardoned", "praised"],
        "correct_answers": ["praised"],
        "explanation": "The word 'rebuked' means to scold or criticize, and its antonym is 'praised,' meaning to commend or express approval, as in 'The prefect praised the student for his behavior.' The other options—'defended' (protected), 'justified' (rationalized), and 'pardoned' (forgave)—do not directly oppose 'rebuked.'",
        "hint": "Select the word that means to commend, the opposite of scolding.",
        "difficulty": "Hard",
        "marks": 1,
        "media_url": "https://example.com/english/antonyms_rebuke.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "antonym", "rebuke"],
        "learning_objectives": ["Identify antonyms", "Understand word opposites"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question assesses advanced antonym knowledge."
      },
      {
        "question": "He normally <u>alights</u> at the station.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Antonyms",
        "options": ["ascends", "boards", "enters", "joins"],
        "correct_answers": ["boards"],
        "explanation": "The word 'alights' means to get off a vehicle, and its antonym is 'boards,' meaning to get on, as in 'He normally boards at the station.' The other options—'ascends' (rises), 'enters' (goes in), and 'joins' (connects)—do not directly oppose the action of getting off a vehicle.",
        "hint": "Choose the word that means to get on, the opposite of getting off a vehicle.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/antonyms_alights.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "antonym", "transport"],
        "learning_objectives": ["Identify antonyms", "Expand vocabulary"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests antonym recognition."
      }
    ],
    "questionCount": 30,
    "total_marks": 30,
    "duration": "2 hours",
    "file_url": "https://example.com/exam/bece_english_2025.pdf",
    "isPublic": true,
    "topics": ["Grammar", "Vocabulary"],
    "difficulty": "Medium",
    "language": "English",
    "status": "Published",
    "instructions": "Select the correct answer for each question."
  }
]