const english_language_2021 = [ 
  {
    "exam_type": "BECE",
    "exam_year": 2019,
    "exam_session": "May/June",
    "region": "Ghana",
    "subject": "English Language",
    "syllabus_version": "2016 Syllabus",
    "questions": [
      {
        "question": "One of the bulls ______ from the herd.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Verb Tense",
        "options": ["have been strayed", "has been strayed", "have stayed", "has strayed"],
        "correct_answers": ["has strayed"],
        "explanation": "The correct answer is 'has strayed' because the subject 'one of the bulls' is singular, requiring the singular verb 'has' in the present perfect tense to indicate a recent action. 'Have been strayed' and 'has been strayed' are passive and grammatically incorrect without a clear agent, while 'have stayed' uses the wrong verb tense and meaning.",
        "hint": "Match the verb to a singular subject in present perfect.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/verb_tense_bulls.jpg",
        "media_type": "image",
        "keywords": ["grammar", "verb", "tense"],
        "learning_objectives": ["Use present perfect tense", "Match subject-verb agreement"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests verb tense and agreement."
      },
      {
        "question": "I saw the dog ______ out of the house.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Verb Forms",
        "options": ["is running", "ran", "running", "was running"],
        "correct_answers": ["running"],
        "explanation": "The correct answer is 'running' because it functions as a gerund or participle complementing 'saw,' indicating the ongoing action of the dog. 'Is running' requires a finite verb form, 'ran' is past tense and lacks context, and 'was running' implies a continuous past action not supported by 'saw' alone.",
        "hint": "Look for a form that describes the action after 'saw'.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/verb_forms_dog.jpg",
        "media_type": "image",
        "keywords": ["grammar", "verb", "gerund"],
        "learning_objectives": ["Use verb forms correctly", "Understand participles"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question evaluates verb form usage."
      },
      {
        "question": "Habib goes to school ______ train.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Prepositions",
        "options": ["by", "on", "with", "in"],
        "correct_answers": ["by"],
        "explanation": "The correct answer is 'by' because it is the standard preposition used to indicate the means of transportation, such as a train. 'On' can be used with specific vehicles like a bus, 'with' implies accompaniment, and 'in' is incorrect for general transportation means.",
        "hint": "Focus on the preposition for transportation means.",
        "difficulty": "Easy",
        "marks": 1,
        "media_url": "https://example.com/english/prepositions_train.jpg",
        "media_type": "image",
        "keywords": ["grammar", "preposition", "transport"],
        "learning_objectives": ["Use prepositions of means", "Identify correct prepositions"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests preposition usage."
      },
      {
        "question": "This phone is not mine; it is ______",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Possessive Pronouns",
        "options": ["my uncle's", "mine uncle's", "my uncles", "mine uncles"],
        "correct_answers": ["my uncle's"],
        "explanation": "The correct answer is 'my uncle's' because it is a possessive form indicating ownership, correctly following the structure after 'is not mine.' 'Mine uncle's' is grammatically incorrect as 'mine' cannot be followed by a noun, 'my uncles' lacks possession, and 'mine uncles' is a double possessive error.",
        "hint": "Use a possessive form to show ownership.",
        "difficulty": "Easy",
        "marks": 1,
        "media_url": "https://example.com/english/possessive_pronouns.jpg",
        "media_type": "image",
        "keywords": ["grammar", "possessive", "pronoun"],
        "learning_objectives": ["Use possessive pronouns", "Understand ownership"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question assesses possessive pronoun usage."
      },
      {
        "question": "Their sister wore a ______ dress to the party.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Adjectives",
        "options": ["silk blue beautiful", "beautiful blue silk", "blue beautiful silk", "beautiful silk blue"],
        "correct_answers": ["beautiful blue silk"],
        "explanation": "In English, adjectives follow a specific order when multiple are used before a noun: opinion, size, age, color, material, noun. In this sentence, 'beautiful' (opinion), 'blue' (color), and 'silk' (material) should be arranged as 'beautiful blue silk,' as in 'Their sister wore a beautiful blue silk dress to the party.' The other options—'silk blue beautiful,' 'blue beautiful silk,' and 'beautiful silk blue'—violate this standard adjective order, making them incorrect.",
        "hint": "Arrange the adjectives in the order of opinion, color, and material before the noun 'dress.'",
        "difficulty": "Easy",
        "marks": 1,
        "media_url": "https://example.com/english/adjective_order.jpg",
        "media_type": "image",
        "keywords": ["grammar", "adjective", "order"],
        "learning_objectives": ["Use adjective order", "Apply correct word order"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests adjective placement."
      },
      {
        "question": "I wish I ______ my friend next week.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Verb Tense",
        "options": ["can visit", "am visiting", "shall visit", "could visit"],
        "correct_answers": ["could visit"],
        "explanation": "The verb 'wish' in this sentence introduces a hypothetical or unreal situation, often requiring the subjunctive mood with a past tense form to express a desire for the future. 'Could visit' is correct, as in 'I wish I could visit my friend next week,' indicating a desired but uncertain or unlikely action. The other options—'can visit' (present ability), 'am visiting' (present continuous), and 'shall visit' (future intention)—do not convey the hypothetical nature required by 'wish' in this context.",
        "hint": "Choose the verb form that expresses a hypothetical or desired action for the future after 'wish.'",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/verb_tense_wish.jpg",
        "media_type": "image",
        "keywords": ["grammar", "verb", "future"],
        "learning_objectives": ["Use future tense", "Understand wish constructions"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question assesses future tense usage."
      },
      {
        "question": "Aba took ______ her mother in many ways.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Phrasal Verbs",
        "options": ["after", "up", "on", "by"],
        "correct_answers": ["after"],
        "explanation": "The correct answer is 'after' because the phrasal verb 'took after' means to resemble or inherit traits, fitting the context of resembling her mother. 'Up,' 'on,' and 'by' do not form meaningful phrasal verbs with 'took' in this context.",
        "hint": "Look for a phrasal verb meaning to resemble.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/phrasal_verbs_took.jpg",
        "media_type": "image",
        "keywords": ["grammar", "phrasal verb", "resemblance"],
        "learning_objectives": ["Use phrasal verbs", "Understand meaning"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests phrasal verb usage."
      },
      {
        "question": "The girl is allergic ______ dust.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Prepositions",
        "options": ["with", "to", "against", "about"],
        "correct_answers": ["to"],
        "explanation": "The correct answer is 'to' because the phrase 'allergic to' is a fixed expression in English, indicating a negative reaction to a substance. 'With,' 'against,' and 'about' do not fit this specific context.",
        "hint": "Choose the correct preposition for allergy context.",
        "difficulty": "Easy",
        "marks": 1,
        "media_url": "https://example.com/english/prepositions_allergic.jpg",
        "media_type": "image",
        "keywords": ["grammar", "preposition", "allergy"],
        "learning_objectives": ["Use prepositions correctly", "Identify fixed expressions"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question assesses preposition usage."
      },
      {
        "question": "My brother, with his children, ______ travelling to Salaga next week.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Subject-Verb Agreement",
        "options": ["is", "are", "was", "were"],
        "correct_answers": ["is"],
        "explanation": "The subject of the sentence is 'My brother,' which is singular, requiring a singular verb. The phrase 'with his children' is a prepositional phrase that does not affect the subject's number. Therefore, 'is' is correct, as in 'My brother, with his children, is travelling to Salaga next week.' The present tense is used for the future action ('next week'). The other options—'are' (plural), 'was' (past singular), and 'were' (past plural)—do not match the singular subject or the sentence's tense.",
        "hint": "Identify the main subject and choose the verb that agrees with its number, ignoring additional phrases.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/subject_verb_agreement.jpg",
        "media_type": "image",
        "keywords": ["grammar", "agreement", "verb"],
        "learning_objectives": ["Apply subject-verb agreement", "Understand phrase impact"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests subject-verb agreement."
      },
      {
        "question": "It is high time we ______ for the meeting.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Subjunctive Mood",
        "options": ["left", "leave", "have to leave", "will leave"],
        "correct_answers": ["left"],
        "explanation": "The correct answer is 'left' because the phrase 'it is high time' requires the past subjunctive to express an urgent or past-due action. 'Leave' is present tense, 'have left' is present perfect, and 'had left' is past perfect, all of which do not fit the subjunctive structure.",
        "hint": "Use a past form for urgency after 'high time'.",
        "difficulty": "Hard",
        "marks": 1,
        "media_url": "https://example.com/english/subjunctive_high_time.jpg",
        "media_type": "image",
        "keywords": ["grammar", "subjunctive", "urgency"],
        "learning_objectives": ["Use subjunctive mood", "Understand tense shifts"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question evaluates subjunctive mood usage."
      },
      {
        "question": "The accused person refused to appear before the ______ panel.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Compound Adjectives",
        "options": ["five-man's", "five-man", "five-men", "five-men's"],
        "correct_answers": ["five-man"],
        "explanation": "The correct answer is 'five-man,' which is a compound adjective describing the panel, as in 'The accused person refused to appear before the five-man panel.' Compound adjectives like 'five-man' are formed by combining a number and a noun, connected with a hyphen, to modify another noun. The other options—'five-man's' (incorrect possessive), 'five-men' (plural, not an adjective), and 'five-men's' (plural possessive)—do not correctly function as a compound adjective in this context.",
        "hint": "Choose the option that correctly forms a compound adjective to describe the panel.",
        "difficulty": "Easy",
        "marks": 1,
        "media_url": "https://example.com/english/prepositions_before.jpg",
        "media_type": "image",
        "keywords": ["grammar", "compound adjective", "hyphenation"],
        "learning_objectives": ["Understand the formation of compound adjectives", "Apply correct hyphenation in descriptive phrases"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question effectively tests the use of compound adjectives. Consider adding a distractor with a different compound structure to enhance difficulty."
      },
      {
        "question": "The stories her children told her made her ______",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Verb Forms",
        "options": ["to laugh", "laughing", "laughed", "laugh"],
        "correct_answers": ["laugh"],
        "explanation": "The correct answer is 'laugh' because it is the base form required after 'made' in a causative construction. 'To laugh' is incorrect as an infinitive, 'laughing' is a gerund/participle not fitting the structure, and 'laughed' is past tense, which doesn't align with the present context.",
        "hint": "Use the base form after 'made'.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/verb_forms_made.jpg",
        "media_type": "image",
        "keywords": ["grammar", "verb", "causative"],
        "learning_objectives": ["Use causative verbs", "Apply correct verb forms"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests causative verb usage."
      },
      {
        "question": "They have not bought ______ of the two prescribed books.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Quantifiers",
        "options": ["neither", "either", "none", "all"],
        "correct_answers": ["neither"],
        "explanation": "The correct answer is 'neither' because it is the appropriate quantifier to indicate that none of the two prescribed books were bought. 'Either' suggests one of two, 'none' is typically used for more than two, and 'all' contradicts the negative 'have not bought'.",
        "hint": "Choose a quantifier for two items with a negative.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/quantifiers_books.jpg",
        "media_type": "image",
        "keywords": ["grammar", "quantifier", "negative"],
        "learning_objectives": ["Use quantifiers", "Understand negative contexts"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question assesses quantifier usage."
      },
      {
        "question": "The boy found the assignment ______ to do.",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Adjectives",
        "options": ["much too difficult", "difficult too much", "too much difficult", "much difficult too"],
        "correct_answers": ["much too difficult"],
        "explanation": "The correct answer is 'much too difficult' because it follows the standard English order of intensifiers and adjectives, with 'much' enhancing 'too difficult.' 'Difficult too much' and 'too much difficult' invert the order incorrectly, while 'much difficult too' is grammatically awkward and incorrect.",
        "hint": "Arrange the intensifier and adjective in the right order.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/adjective_order_assignment.jpg",
        "media_type": "image",
        "keywords": ["grammar", "adjective", "intensifier"],
        "learning_objectives": ["Use adjective order", "Apply intensifiers"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests adjective and intensifier placement."
      },
      {
        "question": "The oxen lay on the bare floor, ______?",
        "question_type": "objective",
        "topic": "Grammar",
        "subtopic": "Question Tags",
        "options": ["didn't they", "don't they", "didn't it", "isn't it"],
        "correct_answers": ["didn't they"],
        "explanation": "The correct answer is 'didn't they' because the subject 'the oxen' is plural, requiring a plural pronoun 'they' in the tag, and the verb 'lay' (past tense) pairs with 'didn't.' 'Don't they' uses present tense, 'didn't it' uses a singular pronoun, and 'isn't it' mismatches tense and number.",
        "hint": "Match the tag to a plural subject and past tense.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/question_tags_oxen.jpg",
        "media_type": "image",
        "keywords": ["grammar", "question tag", "plural"],
        "learning_objectives": ["Use question tags", "Match tense and number"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question evaluates question tag formation."
      },
      {
        "question": "The officials made a <u>sudden</u> visit to the school.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Synonyms",
        "options": ["an unusual", "a strange", "a quick", "an unexpected"],
        "correct_answers": ["an unexpected"],
        "explanation": "The correct answer is 'an unexpected' because it is a synonym for 'sudden,' meaning occurring without warning or preparation. 'An unusual' implies rarity, 'a strange' suggests oddity, and 'a quick' relates to speed rather than suddenness.",
        "hint": "Look for a word meaning occurring without warning.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/synonyms_sudden.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "synonym", "unexpected"],
        "learning_objectives": ["Identify synonyms", "Understand word meanings"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests synonym recognition."
      },
      {
        "question": "Some of the students <u>grumbled</u> about the assignment.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Synonyms",
        "options": ["questioned", "talked", "complained", "bothered"],
        "correct_answers": ["complained"],
        "explanation": "The correct answer is 'complained' because it is a synonym for 'grumbled,' meaning to express dissatisfaction. 'Questioned' implies inquiry, 'talked' is neutral, and 'bothered' suggests annoyance without vocal expression.",
        "hint": "Look for a word meaning to express dissatisfaction.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/synonyms_grumbled.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "synonym", "dissatisfaction"],
        "learning_objectives": ["Identify synonyms", "Understand word meanings"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests synonym recognition."
      },
      {
        "question": "It is <u>impolite</u> to talk loudly in the presence of the elderly.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Antonyms",
        "options": ["incorrect", "improper", "unwise", "rude"],
        "correct_answers": ["rude"],
        "explanation": "The correct answer is 'rude' because it is the antonym of 'impolite,' which means lacking good manners or courtesy. 'Incorrect' and 'improper' suggest wrongness but not specifically related to manners, while 'unwise' relates to judgment rather than politeness.",
        "hint": "Look for the opposite of courteous behavior.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/antonyms_impolite.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "antonym", "politeness"],
        "learning_objectives": ["Identify antonyms", "Understand social behavior"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question assesses antonym knowledge."
      },
      {
        "question": "She is fond of talking about <u>trivial</u> matters.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Antonyms",
        "options": ["unpleasant", "unimportant", "unexciting", "unacceptable"],
        "correct_answers": ["unimportant"],
        "explanation": "The correct answer is 'unimportant' because it is the antonym of 'trivial,' which means of little value or significance, while 'unimportant' directly opposes this. 'Unpleasant' relates to feelings, 'unexciting' to interest, and 'unacceptable' to acceptability, none of which are direct opposites.",
        "hint": "Look for the opposite of significant.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/antonyms_trivial.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "antonym", "significance"],
        "learning_objectives": ["Identify antonyms", "Expand vocabulary"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests antonym comprehension."
      },
      {
        "question": "This <u>curious</u> child likes to ask a lot of questions.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Synonyms",
        "options": ["inquisitive", "pompous", "intelligent", "talkative"],
        "correct_answers": ["inquisitive"],
        "explanation": "The correct answer is 'inquisitive' because it is a synonym for 'curious,' meaning eager to learn or ask questions. 'Pompous' implies arrogance, 'intelligent' focuses on intellect, and 'talkative' emphasizes speech volume, none of which fully match 'curious'.",
        "hint": "Find a word meaning eager to learn.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/synonyms_curious.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "synonym", "curiosity"],
        "learning_objectives": ["Identify synonyms", "Understand word meanings"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question evaluates synonym recognition."
      },
      {
        "question": "Arabah's visit was a <u>bolt from the blue</u>. This means that the visit was",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Idioms",
        "options": ["a most welcome one", "short", "a complete surprise", "timely"],
        "correct_answers": ["a complete surprise"],
        "explanation": "The correct answer is 'a complete surprise' because the idiom 'a bolt from the blue' means something unexpected or surprising. 'A most welcome one' and 'timely' suggest positive anticipation, while 'short' is unrelated to the idiom's meaning.",
        "hint": "Think of an idiom meaning something unexpected.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/idioms_bolt_blue.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "idiom", "surprise"],
        "learning_objectives": ["Interpret idioms", "Understand figurative language"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests idiom comprehension."
      },
      {
        "question": "My uncle loves to <u>cast his bread upon the waters</u>. This means that my uncle",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Idioms",
        "options": ["behaves strangely", "feeds his fish with bread", "is wasteful", "loves to help people"],
        "correct_answers": ["loves to help people"],
        "explanation": "The correct answer is 'loves to help people' because the idiom 'cast his bread upon the waters' means to give generously with the hope of future reward, making 'loves to help people' the most fitting interpretation. 'Behaves strangely' and 'feeds his fish with bread' are literal misinterpretations, while 'is wasteful' contradicts the idiom's positive connotation of generosity.",
        "hint": "Consider an idiom about giving with hope of return.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/idioms_cast_bread.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "idiom", "generosity"],
        "learning_objectives": ["Interpret idioms", "Understand figurative language"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests comprehension of idiomatic expressions."
      },
      {
        "question": "When he lost his job, Yaro was <u>left to sink or swim</u>. This means that Yaro",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Idioms",
        "options": ["was depressed", "shouted for help", "had to find another job", "had to survive on his own"],
        "correct_answers": ["had to survive on his own"],
        "explanation": "The correct answer is 'had to survive on his own' because the idiom 'sink or swim' means to either succeed or fail based on one's own efforts, fitting Yaro's situation after job loss. 'Was depressed' and 'shouted for help' suggest emotional reactions rather than action, while 'had to find another job' is too specific and not implied by the idiom.",
        "hint": "Think about an idiom meaning to manage alone.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/idioms_sink_swim.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "idiom", "self-reliance"],
        "learning_objectives": ["Interpret idioms", "Apply figurative meanings"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question evaluates idiom understanding."
      },
      {
        "question": "I was informed <u>at the eleventh hour</u> about his decision to leave. This means that I heard about his decision",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Idioms",
        "options": ["immediately", "at eleven o'clock", "in good time", "very late"],
        "correct_answers": ["very late"],
        "explanation": "The correct answer is 'very late' because the idiom 'at the eleventh hour' refers to the last possible moment, indicating the information was received just before the decision took effect. 'Immediately' suggests promptness, 'at eleven o'clock' is a literal misinterpretation, and 'in good time' contradicts the idiom's meaning of delay.",
        "hint": "Focus on a phrase meaning just before the end.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/idioms_eleventh_hour.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "idiom", "timing"],
        "learning_objectives": ["Understand idioms", "Interpret time-related phrases"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests idiom interpretation."
      },
      {
        "question": "John had to <u>eat his words</u> when our team won the match. This means that John",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Idioms",
        "options": ["became very much surprised", "admitted he was wrong", "denied all that he had said", "lost appetite"],
        "correct_answers": ["admitted he was wrong"],
        "explanation": "The correct answer is 'admitted he was wrong' because the idiom 'eat his words' means to retract or acknowledge a previous statement as incorrect, fitting John's reaction to his team's win. 'Became very much surprised' and 'lost appetite' are unrelated to retracting statements, while 'denied all that he had said' contradicts the idiom's meaning of admission.",
        "hint": "Think about retracting a statement after an event.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/idioms_eat_words.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "idiom", "retraction"],
        "learning_objectives": ["Interpret idioms", "Apply figurative language"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question assesses idiom comprehension."
      },
      {
        "question": "The girl <u>intentionally</u> tore her dress.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Antonyms",
        "options": ["carelessly", "accidentally", "willingly", "foolishly"],
        "correct_answers": ["accidentally"],
        "explanation": "The correct answer is 'accidentally' because it is the antonym of 'intentionally,' which means doing something on purpose, whereas 'accidentally' implies an unintended action. 'Carelessly' and 'foolishly' suggest negligence but not lack of intent, while 'willingly' aligns with intent rather than opposing it.",
        "hint": "Look for the opposite of doing something on purpose.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/antonyms_intentionally.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "antonym", "intent"],
        "learning_objectives": ["Identify antonyms", "Understand word opposites"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests antonym recognition."
      },
      {
        "question": "We <u>initiated</u> several projects last year.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Antonyms",
        "options": ["funded", "completed", "executed", "organized"],
        "correct_answers": ["completed"],
        "explanation": "The correct answer is 'completed' because it is the antonym of 'initiated,' which means to start, while 'completed' means to finish. 'Funded,' 'executed,' and 'organized' are related to starting or managing projects but do not directly oppose the action of initiation.",
        "hint": "Think of the opposite of starting something.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/antonyms_initiated.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "antonym", "start"],
        "learning_objectives": ["Identify antonyms", "Expand vocabulary"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question evaluates antonym understanding."
      },
      {
        "question": "Most of the rules were <u>observed</u>.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Antonyms",
        "options": ["violated", "cancelled", "lessened", "excluded"],
        "correct_answers": ["violated"],
        "explanation": "The correct answer is 'violated' because it is the antonym of 'observed,' which means to follow or adhere to, while 'violated' means to break or disregard. 'Cancelled,' 'lessened,' and 'excluded' involve altering or removing rules but do not directly oppose observance.",
        "hint": "Look for the opposite of following rules.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/antonyms_observed.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "antonym", "rules"],
        "learning_objectives": ["Identify antonyms", "Understand word meanings"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests antonym recognition."
      },
      {
        "question": "The results will be <u>released</u> very soon.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Antonyms",
        "options": ["withheld", "confirmed", "withdrawn", "cancelled"],
        "correct_answers": ["withheld"],
        "explanation": "The correct answer is 'withheld' because it is the antonym of 'released,' which means to make available, while 'withheld' means to hold back. 'Confirmed,' 'withdrawn,' and 'cancelled' involve different actions related to results but do not directly oppose release.",
        "hint": "Think of the opposite of making something available.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/antonyms_released.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "antonym", "release"],
        "learning_objectives": ["Identify antonyms", "Expand vocabulary"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question assesses antonym knowledge."
      },
      {
        "question": "No one enjoyed the old man's <u>humourless</u> stories.",
        "question_type": "objective",
        "topic": "Vocabulary",
        "subtopic": "Antonyms",
        "options": ["funny", "peculiar", "familiar", "cheerful"],
        "correct_answers": ["funny"],
        "explanation": "The correct answer is 'funny' because it is the antonym of 'humourless,' which means lacking humor, while 'funny' means amusing. 'Peculiar' and 'familiar' describe different qualities, and 'cheerful' relates to mood rather than humor.",
        "hint": "Look for the opposite of lacking humor.",
        "difficulty": "Medium",
        "marks": 1,
        "media_url": "https://example.com/english/antonyms_humourless.jpg",
        "media_type": "image",
        "keywords": ["vocabulary", "antonym", "humor"],
        "learning_objectives": ["Identify antonyms", "Understand word opposites"],
        "estimated_time": "2 minutes",
        "source_reference": "WAEC Past Questions",
        "ai_feedback": "This question tests antonym comprehension."
      },
    ],
    "questionCount": 30,
    "total_marks": 30,
    "duration": "1 hour 30 minutes",
    "file_url": "https://example.com/exam/bece_english_2025_section_d.pdf",
    "isPublic": true,
    "topics": ["Vocabulary", "Grammar"],
    "difficulty": "Medium",
    "language": "English",
    "status": "Published",
    "instructions": "Select the correct answer for each question."
  }
]