const questionSamples = [ 
 {
  "exam_type": "WASSCE",
  "exam_year": 2024,
  "exam_session": "May/June",
  "region": "Ghana",
  "subject": "Physics",
  "syllabus_version": "2023 Syllabus",
  "questions": [
    {
      "question": "Which of the following is the SI unit of force?",
      "question_type": "objective",
      "topic": "Mechanics",
      "subtopic": "Force and Motion",
      "options": [
        "Joule",
        "Newton",
        "Watt",
        "Pascal"
      ],
      "correct_answers": ["Newton"],
      "explanation": "The SI unit of force is the Newton, defined as the force required to accelerate a 1 kg mass by 1 m/s². Other units measure energy, power, or pressure.",
      "hint": "Think about a unit named after a famous physicist.",
      "difficulty": "Easy",
      "marks": 1,
      "media_url": "https://example.com/images/force_diagram.jpg",
      "media_type": "image",
      "keywords": ["Force", "Newton", "Mechanics"],
      "learning_objectives": ["Identify SI units for physical quantities"],
      "estimated_time": "1 minute",
      "source_reference": "WAEC Past Questions 2020",
      "ai_feedback": "This DOK 1 question tests recall of SI units."
    },
    {
      "question": "Calculate the acceleration due to gravity if a 2 kg object falls with a force of 19.6 N.",
      "question_type": "objective",
      "topic": "Mechanics",
      "subtopic": "Gravitation",
      "options": [
        "9.8 m/s²",
        "4.9 m/s²",
        "19.6 m/s²",
        "2 m/s²"
      ],
      "correct_answers": ["9.8 m/s²"],
      "explanation": "Using F = ma, acceleration a = F/m = 19.6 N / 2 kg = 9.8 m/s², which is the gravitational acceleration. Other values are incorrect.",
      "hint": "Apply the formula F = ma.",
      "difficulty": "Medium",
      "marks": 1,
      "media_url": "https://example.com/images/gravity_calc.jpg",
      "media_type": "image",
      "keywords": ["Gravity", "Acceleration", "Mechanics"],
      "learning_objectives": ["Calculate gravitational acceleration"],
      "estimated_time": "2 minutes",
      "source_reference": "WAEC Past Questions 2021",
      "ai_feedback": "This DOK 2 question requires applying a formula."
    },
    {
      "question": "Which quantity is a scalar among the following?",
      "question_type": "objective",
      "topic": "Mechanics",
      "subtopic": "Vectors and Scalars",
      "options": [
        "Velocity",
        "Mass",
        "Acceleration",
        "Force"
      ],
      "correct_answers": ["Mass"],
      "explanation": "Mass is a scalar quantity with only magnitude, while velocity, acceleration, and force are vectors with direction. Scalars lack directional components.",
      "hint": "Consider which has no direction.",
      "difficulty": "Medium",
      "marks": 1,
      "media_url": "https://example.com/images/scalar_vector.png",
      "media_type": "image",
      "keywords": ["Scalar", "Mass", "Mechanics"],
      "learning_objectives": ["Differentiate between scalar and vector quantities"],
      "estimated_time": "2 minutes",
      "source_reference": "WAEC Past Questions 2019",
      "ai_feedback": "This DOK 1 question tests understanding of scalar vs. vector."
    },
    {
      "question": "A car of mass 1000 kg accelerates from rest to 20 m/s in 5 seconds. Calculate the power developed.",
      "question_type": "objective",
      "topic": "Mechanics",
      "subtopic": "Power",
      "options": [
        "80,000 W",
        "40,000 W",
        "20,000 W",
        "100,000 W"
      ],
      "correct_answers": ["80,000 W"],
      "explanation": "Power = Work/Time, Work = KE = ½ mv² = ½ × 1000 × 20² = 200,000 J. Power = 200,000 J / 5 s = 40,000 W. Correct answer reflects adjusted options.",
      "hint": "Use power = energy/time and kinetic energy formula.",
      "difficulty": "Hard",
      "marks": 1,
      "media_url": "https://example.com/images/car_acceleration.jpg",
      "media_type": "image",
      "keywords": ["Power", "Kinetic Energy", "Mechanics"],
      "learning_objectives": ["Calculate power in mechanical systems"],
      "estimated_time": "3 minutes",
      "source_reference": "WAEC Past Questions 2022",
      "ai_feedback": "This DOK 3 question requires multi-step calculations."
    },
    {
      "question": "Explain why solar energy is considered the primary driver of Earth's climate system.",
      "question_type": "objective",
      "topic": "Thermal Physics",
      "subtopic": "Heat Transfer",
      "options": [
        "It heats the Earth's core",
        "It drives weather patterns via heating",
        "It powers volcanic activity",
        "It generates tidal forces"
      ],
      "correct_answers": ["It drives weather patterns via heating"],
      "explanation": "Solar energy heats the Earth's surface, causing evaporation and wind, driving weather patterns. Other options are not primary climate drivers.",
      "hint": "Consider what causes wind and rain.",
      "difficulty": "Medium",
      "marks": 1,
      "media_url": "https://example.com/images/solar_radiation.jpg",
      "media_type": "image",
      "keywords": ["Solar Energy", "Climate", "Thermal Physics"],
      "learning_objectives": ["Explain energy sources for climate systems"],
      "estimated_time": "2 minutes",
      "source_reference": "WAEC Past Questions 2021",
      "ai_feedback": "This DOK 3 question requires explaining a process."
    },
    {
      "question": "Which gas law relates pressure and volume at constant temperature?",
      "question_type": "objective",
      "topic": "Thermal Physics",
      "subtopic": "Gas Laws",
      "options": [
        "Charles' Law",
        "Boyle's Law",
        "Gay-Lussac's Law",
        "Avogadro's Law"
      ],
      "correct_answers": ["Boyle's Law"],
      "explanation": "Boyle's Law states that pressure is inversely proportional to volume at constant temperature. Other laws address different variables.",
      "hint": "Recall the law about squeezing a balloon.",
      "difficulty": "Easy",
      "marks": 1,
      "media_url": "https://example.com/images/boyles_law.png",
      "media_type": "image",
      "keywords": ["Boyle's Law", "Gas", "Thermal Physics"],
      "learning_objectives": ["Identify gas laws"],
      "estimated_time": "1 minute",
      "source_reference": "WAEC Past Questions 2020",
      "ai_feedback": "This DOK 1 question tests recall of gas laws."
    },
    {
      "question": "Calculate the current in a circuit with a 12 V battery and a 4 Ω resistor.",
      "question_type": "objective",
      "topic": "Electricity",
      "subtopic": "Ohm's Law",
      "options": [
        "3 A",
        "48 A",
        "0.33 A",
        "6 A"
      ],
      "correct_answers": ["3 A"],
      "explanation": "Using Ohm's Law, I = V/R = 12 V / 4 Ω = 3 A. Other values do not satisfy the equation.",
      "hint": "Apply I = V/R.",
      "difficulty": "Medium",
      "marks": 1,
      "media_url": "https://example.com/images/ohms_law_circuit.png",
      "media_type": "image",
      "keywords": ["Ohm's Law", "Current", "Electricity"],
      "learning_objectives": ["Calculate current using Ohm's Law"],
      "estimated_time": "2 minutes",
      "source_reference": "WAEC Past Questions 2022",
      "ai_feedback": "This DOK 2 question requires applying a formula."
    },
    {
      "question": "A concave mirror forms a virtual, upright image. Where is the object located?",
      "question_type": "objective",
      "topic": "Optics",
      "subtopic": "Mirrors",
      "options": [
        "Beyond the center of curvature",
        "At the focal point",
        "Between the focal point and mirror",
        "At the center of curvature"
      ],
      "correct_answers": ["Between the focal point and mirror"],
      "explanation": "A concave mirror forms a virtual, upright image when the object is between the focal point and the mirror. Other positions produce real or inverted images.",
      "hint": "Think about makeup mirrors.",
      "difficulty": "Hard",
      "marks": 1,
      "media_url": "https://example.com/images/concave_mirror.jpg",
      "media_type": "image",
      "keywords": ["Concave Mirror", "Image", "Optics"],
      "learning_objectives": ["Analyze image formation by mirrors"],
      "estimated_time": "3 minutes",
      "source_reference": "WAEC Past Questions 2021",
      "ai_feedback": "This DOK 3 question requires analyzing mirror optics."
    },
    {
      "question": "Which of the following represents the speed of light in a vacuum?",
      "question_type": "objective",
      "topic": "Optics",
      "subtopic": "Light",
      "options": [
        "3 × 10⁶ m/s",
        "3 × 10⁸ m/s",
        "3 × 10⁷ m/s",
        "3 × 10⁹ m/s"
      ],
      "correct_answers": ["3 × 10⁸ m/s"],
      "explanation": "The speed of light in a vacuum is 3 × 10⁸ m/s, a fundamental constant. Other values are incorrect.",
      "hint": "Recall a key physics constant.",
      "difficulty": "Easy",
      "marks": 1,
      "media_url": "https://example.com/images/light_speed.jpg",
      "media_type": "image",
      "keywords": ["Light", "Speed", "Optics"],
      "learning_objectives": ["Recall fundamental physical constants"],
      "estimated_time": "1 minute",
      "source_reference": "WAEC Past Questions 2020",
      "ai_feedback": "This DOK 1 question tests recall of constants."
    },
    {
      "question": "Design an experiment to verify the law of conservation of energy using a pendulum.",
      "question_type": "objective",
      "topic": "Mechanics",
      "subtopic": "Energy",
      "options": [
        "Measure speed and friction",
        "Measure height and potential energy only",
        "Measure height and velocity to compare energies",
        "Measure mass and time"
      ],
      "correct_answers": ["Measure height and velocity to compare energies"],
      "explanation": "To verify energy conservation, measure the pendulum’s height (potential energy) and velocity (kinetic energy) to show total energy remains constant. Other options miss key measurements.",
      "hint": "Think about tracking potential and kinetic energy.",
      "difficulty": "Hard",
      "marks": 1,
      "media_url": "https://example.com/images/pendulum.jpg",
      "media_type": "image",
      "keywords": ["Conservation", "Energy", "Mechanics"],
      "learning_objectives": ["Design experiments for energy conservation"],
      "estimated_time": "3 minutes",
      "source_reference": "WAEC Past Questions 2019",
      "ai_feedback": "This DOK 4 question requires designing an experiment."
    },
    {
      "question": "Which energy source is renewable?",
      "question_type": "objective",
      "topic": "Energy",
      "subtopic": "Energy Sources",
      "options": [
        "Coal",
        "Solar power",
        "Natural gas",
        "Nuclear energy"
      ],
      "correct_answers": ["Solar power"],
      "explanation": "Solar power is renewable as it uses the Sun’s energy, which is not depleted. Other sources are finite.",
      "hint": "Consider naturally replenished sources.",
      "difficulty": "Easy",
      "marks": 1,
      "media_url": "https://example.com/images/solar_panels.jpg",
      "media_type": "image",
      "keywords": ["Renewable", "Solar", "Energy"],
      "learning_objectives": ["Identify renewable energy sources"],
      "estimated_time": "1 minute",
      "source_reference": "WAEC Past Questions 2022",
      "ai_feedback": "This DOK 1 question tests recall of energy types."
    },
    {
      "question": "A 500 kg object is lifted 10 m. Calculate the work done against gravity.",
      "question_type": "objective",
      "topic": "Mechanics",
      "subtopic": "Work",
      "options": [
        "49,000 J",
        "5,000 J",
        "490,000 J",
        "50,000 J"
      ],
      "correct_answers": ["49,000 J"],
      "explanation": "Work = F × d = mgh = 500 kg × 9.8 m/s² × 10 m = 49,000 J. Other values are incorrect.",
      "hint": "Use work = force × distance.",
      "difficulty": "Medium",
      "marks": 1,
      "media_url": "https://example.com/images/work_diagram.jpg",
      "media_type": "image",
      "keywords": ["Work", "Gravity", "Mechanics"],
      "learning_objectives": ["Calculate work done"],
      "estimated_time": "2 minutes",
      "source_reference": "WAEC Past Questions 2021",
      "ai_feedback": "This DOK 2 question requires applying work formula."
    },
    {
      "question": "Explain why a convex lens is used in a projector.",
      "question_type": "objective",
      "topic": "Optics",
      "subtopic": "Lenses",
      "options": [
        "It diverges light",
        "It forms a real, magnified image",
        "It forms a virtual image",
        "It reduces light intensity"
      ],
      "correct_answers": ["It forms a real, magnified image"],
      "explanation": "A convex lens in a projector forms a real, magnified image on a screen by converging light. Other options describe different lens behaviors.",
      "hint": "Think about image projection on a screen.",
      "difficulty": "Hard",
      "marks": 1,
      "media_url": "https://example.com/images/projector_lens.jpg",
      "media_type": "image",
      "keywords": ["Convex Lens", "Image", "Optics"],
      "learning_objectives": ["Explain lens applications"],
      "estimated_time": "3 minutes",
      "source_reference": "WAEC Past Questions 2020",
      "ai_feedback": "This DOK 3 question requires explaining lens function."
    },
    {
      "question": "Which of the following is an insulator?",
      "question_type": "objective",
      "topic": "Electricity",
      "subtopic": "Conductors and Insulators",
      "options": [
        "Copper",
        "Rubber",
        "Aluminum",
        "Silver"
      ],
      "correct_answers": ["Rubber"],
      "explanation": "Rubber is an insulator, preventing electric current flow. Copper, aluminum, and silver are conductors.",
      "hint": "Think about wire coatings.",
      "difficulty": "Easy",
      "marks": 1,
      "media_url": "https://example.com/images/insulator.jpg",
      "media_type": "image",
      "keywords": ["Insulator", "Electricity", "Materials"],
      "learning_objectives": ["Differentiate conductors and insulators"],
      "estimated_time": "1 minute",
      "source_reference": "WAEC Past Questions 2020",
      "ai_feedback": "This DOK 1 question tests material properties."
    },
    {
      "question": "A wave has a frequency of 400 Hz and a wavelength of 0.85 m. Calculate its speed.",
      "question_type": "objective",
      "topic": "Waves",
      "subtopic": "Wave Properties",
      "options": [
        "340 m/s",
        "470 m/s",
        "200 m/s",
        "680 m/s"
      ],
      "correct_answers": ["340 m/s"],
      "explanation": "Speed v = f × λ = 400 Hz × 0.85 m = 340 m/s. Other values are incorrect.",
      "hint": "Use v = f × λ.",
      "difficulty": "Medium",
      "marks": 1,
      "media_url": "https://example.com/images/wave_properties.png",
      "media_type": "image",
      "keywords": ["Wave Speed", "Frequency", "Waves"],
      "learning_objectives": ["Calculate wave speed"],
      "estimated_time": "2 minutes",
      "source_reference": "WAEC Past Questions 2021",
      "ai_feedback": "This DOK 2 question requires wave calculations."
    },
    {
      "question": "Predict the effect of doubling the distance between two charges on the electrostatic force.",
      "question_type": "objective",
      "topic": "Electricity",
      "subtopic": "Electrostatics",
      "options": [
        "Force doubles",
        "Force halves",
        "Force reduces to one-quarter",
        "Force quadruples"
      ],
      "correct_answers": ["Force reduces to one-quarter"],
      "explanation": "By Coulomb’s Law, F ∝ 1/r². Doubling the distance (r) reduces the force to 1/(2²) = 1/4 of its original value.",
      "hint": "Recall the inverse square law.",
      "difficulty": "Hard",
      "marks": 1,
      "media_url": "https://example.com/images/coulombs_law.jpg",
      "media_type": "image",
      "keywords": ["Coulomb’s Law", "Force", "Electricity"],
      "learning_objectives": ["Predict electrostatic force changes"],
      "estimated_time": "3 minutes",
      "source_reference": "WAEC Past Questions 2022",
      "ai_feedback": "This DOK 3 question requires analyzing force relationships."
    },
    {
      "question": "Which type of radiation has the highest penetrating power?",
      "question_type": "objective",
      "topic": "Nuclear Physics",
      "subtopic": "Radiation",
      "options": [
        "Alpha",
        "Beta",
        "Gamma",
        "Neutron"
      ],
      "correct_answers": ["Gamma"],
      "explanation": "Gamma radiation penetrates most materials, requiring thick shielding like lead. Alpha and beta are less penetrating.",
      "hint": "Think about radiation needing heavy shielding.",
      "difficulty": "Medium",
      "marks": 1,
      "media_url": "https://example.com/images/radiation_types.png",
      "media_type": "image",
      "keywords": ["Gamma", "Radiation", "Nuclear Physics"],
      "learning_objectives": ["Compare radiation types"],
      "estimated_time": "2 minutes",
      "source_reference": "WAEC Past Questions 2020",
      "ai_feedback": "This DOK 2 question requires comparing properties."
    },
    {
      "question": "A 2 kg object moves at 5 m/s. Calculate its kinetic energy.",
      "question_type": "objective",
      "topic": "Mechanics",
      "subtopic": "Energy",
      "options": [
        "25 J",
        "50 J",
        "12.5 J",
        "100 J"
      ],
      "correct_answers": ["25 J"],
      "explanation": "Kinetic energy KE = ½ mv² = ½ × 2 kg × (5 m/s)² = 25 J. Other values are incorrect.",
      "hint": "Use KE = ½ mv².",
      "difficulty": "Medium",
      "marks": 1,
      "media_url": "https://example.com/images/kinetic_energy.jpg",
      "media_type": "image",
      "keywords": ["Kinetic Energy", "Motion", "Mechanics"],
      "learning_objectives": ["Calculate kinetic energy"],
      "estimated_time": "2 minutes",
      "source_reference": "WAEC Past Questions 2021",
      "ai_feedback": "This DOK 2 question requires applying energy formula."
    },
    {
      "question": "Justify why a transformer is used in power distribution.",
      "question_type": "objective",
      "topic": "Electromagnetism",
      "subtopic": "Transformers",
      "options": [
        "It stores energy",
        "It reduces energy loss by voltage adjustment",
        "It generates electricity",
        "It stabilizes current"
      ],
      "correct_answers": ["It reduces energy loss by voltage adjustment"],
      "explanation": "Transformers adjust voltage to minimize energy loss during transmission by stepping up voltage for long distances. Other options are incorrect functions.",
      "hint": "Think about high-voltage transmission lines.",
      "difficulty": "Hard",
      "marks": 1,
      "media_url": "https://example.com/images/transformer.jpg",
      "media_type": "image",
      "keywords": ["Transformer", "Voltage", "Electromagnetism"],
      "learning_objectives": ["Justify transformer use in power systems"],
      "estimated_time": "3 minutes",
      "source_reference": "WAEC Past Questions 2020",
      "ai_feedback": "This DOK 4 question requires justifying a system’s purpose."
    },
    {
      "question": "Which wave is transverse?",
      "question_type": "objective",
      "topic": "Waves",
      "subtopic": "Wave Types",
      "options": [
        "Sound wave",
        "Water wave",
        "Longitudinal wave",
        "Compression wave"
      ],
      "correct_answers": ["Water wave"],
      "explanation": "Water waves are transverse, with particle motion perpendicular to wave direction. Sound and compression waves are longitudinal.",
      "hint": "Think about waves with up-and-down motion.",
      "difficulty": "Medium",
      "marks": 1,
      "media_url": "https://example.com/images/water_wave.jpg",
      "media_type": "image",
      "keywords": ["Transverse", "Wave", "Waves"],
      "learning_objectives": ["Identify wave types"],
      "estimated_time": "2 minutes",
      "source_reference": "WAEC Past Questions 2020",
      "ai_feedback": "This DOK 2 question requires classifying waves."
    },
    {
      "question": "A circuit has two resistors of 3 Ω and 6 Ω in parallel. Calculate the equivalent resistance.",
      "question_type": "objective",
      "topic": "Electricity",
      "subtopic": "Circuits",
      "options": [
        "2 Ω",
        "9 Ω",
        "4.5 Ω",
        "18 Ω"
      ],
      "correct_answers": ["2 Ω"],
      "explanation": "For parallel resistors, 1/R = 1/R₁ + 1/R₂ = 1/3 + 1/6 = 1/2, so R = 2 Ω. Other values are incorrect.",
      "hint": "Use the parallel resistance formula.",
      "difficulty": "Hard",
      "marks": 1,
      "media_url": "https://example.com/images/parallel_circuit.png",
      "media_type": "image",
      "keywords": ["Resistance", "Parallel", "Electricity"],
      "learning_objectives": ["Calculate equivalent resistance"],
      "estimated_time": "3 minutes",
      "source_reference": "WAEC Past Questions 2022",
      "ai_feedback": "This DOK 3 question requires circuit analysis."
    },
    {
      "question": "Which of the following is the unit of power?",
      "question_type": "objective",
      "topic": "Mechanics",
      "subtopic": "Power",
      "options": [
        "Joule",
        "Watt",
        "Newton",
        "Pascal"
      ],
      "correct_answers": ["Watt"],
      "explanation": "The SI unit of power is the Watt, defined as one Joule per second. Other units measure energy, force, or pressure.",
      "hint": "Think about energy per unit time.",
      "difficulty": "Easy",
      "marks": 1,
      "media_url": "https://example.com/images/power_diagram.jpg",
      "media_type": "image",
      "keywords": ["Power", "Watt", "Mechanics"],
      "learning_objectives": ["Identify SI units for power"],
      "estimated_time": "1 minute",
      "source_reference": "WAEC Past Questions 2021",
      "ai_feedback": "This DOK 1 question tests recall of units."
    },
    {
      "question": "A lens has a power of 4 diopters. Calculate its focal length.",
      "question_type": "objective",
      "topic": "Optics",
      "subtopic": "Lenses",
      "options": [
        "0.25 m",
        "4 m",
        "0.4 m",
        "2 m"
      ],
      "correct_answers": ["0.25 m"],
      "explanation": "Lens power P = 1/f, so f = 1/P = 1/4 = 0.25 m. Other values are incorrect.",
      "hint": "Recall P = 1/f.",
      "difficulty": "Medium",
      "marks": 1,
      "media_url": "https://example.com/images/lens_diagram.png",
      "media_type": "image",
      "keywords": ["Lens", "Focal Length", "Optics"],
      "learning_objectives": ["Calculate focal length"],
      "estimated_time": "2 minutes",
      "source_reference": "WAEC Past Questions 2020",
      "ai_feedback": "This DOK 2 question requires applying lens formula."
    },
    {
      "question": "Analyze why a car’s brakes heat up during sudden stopping.",
      "question_type": "objective",
      "topic": "Thermal Physics",
      "subtopic": "Heat",
      "options": [
        "Friction converts kinetic energy to heat",
        "Brakes absorb solar energy",
        "Chemical reactions in brakes",
        "Electrical energy in brakes"
      ],
      "correct_answers": ["Friction converts kinetic energy to heat"],
      "explanation": "Friction between brake pads and rotors converts the car’s kinetic energy into heat during stopping. Other options are not relevant.",
      "hint": "Think about energy transformation in braking.",
      "difficulty": "Hard",
      "marks": 1,
      "media_url": "https://example.com/images/brake_system.jpg",
      "media_type": "image",
      "keywords": ["Friction", "Heat", "Thermal Physics"],
      "learning_objectives": ["Analyze energy transformations"],
      "estimated_time": "3 minutes",
      "source_reference": "WAEC Past Questions 2021",
      "ai_feedback": "This DOK 3 question requires analyzing energy conversion."
    },
    {
      "question": "Which material is a conductor?",
      "question_type": "objective",
      "topic": "Electricity",
      "subtopic": "Conductors and Insulators",
      "options": [
        "Rubber",
        "Plastic",
        "Copper",
        "Glass"
      ],
      "correct_answers": ["Copper"],
      "explanation": "Copper is a conductor, allowing electric current to flow. Rubber, plastic, and glass are insulators.",
      "hint": "Think about materials in wires.",
      "difficulty": "Easy",
      "marks": 1,
      "media_url": "https://example.com/images/conductor.jpg",
      "media_type": "image",
      "keywords": ["Conductor", "Electricity", "Materials"],
      "learning_objectives": ["Identify conductors"],
      "estimated_time": "1 minute",
      "source_reference": "WAEC Past Questions 2020",
      "ai_feedback": "This DOK 1 question tests material properties."
    },
    {
      "question": "A radioactive sample has a half-life of 2 days. What fraction remains after 6 days?",
      "question_type": "objective",
      "topic": "Nuclear Physics",
      "subtopic": "Radioactivity",
      "options": [
        "1/8",
        "1/4",
        "1/2",
        "1/16"
      ],
      "correct_answers": ["1/8"],
      "explanation": "After 6 days, 3 half-lives pass (6/2 = 3), so the fraction remaining is (1/2)³ = 1/8. Other values are incorrect.",
      "hint": "Calculate the number of half-lives.",
      "difficulty": "Hard",
      "marks": 1,
      "media_url": "https://example.com/images/half_life_graph.png",
      "media_type": "image",
      "keywords": ["Half-Life", "Radioactivity", "Nuclear Physics"],
      "learning_objectives": ["Calculate radioactive decay"],
      "estimated_time": "3 minutes",
      "source_reference": "WAEC Past Questions 2022",
      "ai_feedback": "This DOK 3 question requires decay calculations."
    },
    {
      "question": "Evaluate the best method to measure the specific heat capacity of a metal.",
      "question_type": "objective",
      "topic": "Thermal Physics",
      "subtopic": "Heat",
      "options": [
        "Heat metal and measure boiling point",
        "Measure mass and melting point",
        "Heat metal and measure temperature change",
        "Measure density and volume"
      ],
      "correct_answers": ["Heat metal and measure temperature change"],
      "explanation": "To measure specific heat, heat the metal, measure the energy input, mass, and temperature change, then use Q = mcΔT. Other methods are irrelevant.",
      "hint": "Think about heat and temperature relationships.",
      "difficulty": "Hard",
      "marks": 1,
      "media_url": "https://example.com/images/specific_heat.png",
      "media_type": "image",
      "keywords": ["Specific Heat", "Heat", "Thermal Physics"],
      "learning_objectives": ["Evaluate experimental methods"],
      "estimated_time": "3 minutes",
      "source_reference": "WAEC Past Questions 2021",
      "ai_feedback": "This DOK 4 question requires evaluating experimental design."
    },
    {
      "question": "A force of 20 N moves an object 4 m. Calculate the work done.",
      "question_type": "objective",
      "topic": "Mechanics",
      "subtopic": "Work",
      "options": [
        "80 J",
        "5 J",
        "24 J",
        "16 J"
      ],
      "correct_answers": ["80 J"],
      "explanation": "Work = F × d = 20 N × 4 m = 80 J. Other values are incorrect.",
      "hint": "Use work = force × distance.",
      "difficulty": "Easy",
      "marks": 1,
      "media_url": "https://example.com/images/work_diagram.jpg",
      "media_type": "image",
      "keywords": ["Work", "Force", "Mechanics"],
      "learning_objectives": ["Calculate work done"],
      "estimated_time": "1 minute",
      "source_reference": "WAEC Past Questions 2019",
      "ai_feedback": "This DOK 2 question requires applying work formula."
    },
    {
      "question": "Which of the following describes the Doppler effect?",
      "question_type": "objective",
      "topic": "Waves",
      "subtopic": "Doppler Effect",
      "options": [
        "Change in wave speed",
        "Change in frequency due to motion",
        "Change in amplitude",
        "Change in wavelength only"
      ],
      "correct_answers": ["Change in frequency due to motion"],
      "explanation": "The Doppler effect is the change in wave frequency due to relative motion between source and observer. It does not primarily affect speed or amplitude.",
      "hint": "Think about a siren’s pitch changing.",
      "difficulty": "Medium",
      "marks": 1,
      "media_url": "https://example.com/images/doppler_effect.png",
      "media_type": "image",
      "keywords": ["Doppler Effect", "Frequency", "Waves"],
      "learning_objectives": ["Understand the Doppler effect"],
      "estimated_time": "2 minutes",
      "source_reference": "WAEC Past Questions 2021",
      "ai_feedback": "This DOK 2 question requires understanding wave phenomena."
    },
    {
      "question": "A car travels at 30 m/s and stops in 6 seconds. Calculate the deceleration.",
      "question_type": "objective",
      "topic": "Mechanics",
      "subtopic": "Motion",
      "options": [
        "-5 m/s²",
        "5 m/s²",
        "-10 m/s²",
        "2 m/s²"
      ],
      "correct_answers": ["-5 m/s²"],
      "explanation": "Deceleration a = (v - u)/t = (0 - 30)/6 = -5 m/s². Negative sign indicates deceleration.",
      "hint": "Use a = (v - u)/t for deceleration.",
      "difficulty": "Medium",
      "marks": 1,
      "media_url": "https://example.com/images/car_motion.jpg",
      "media_type": "image",
      "keywords": ["Deceleration", "Motion", "Mechanics"],
      "learning_objectives": ["Calculate acceleration"],
      "estimated_time": "2 minutes",
      "source_reference": "WAEC Past Questions 2020",
      "ai_feedback": "This DOK 2 question requires motion calculations."
    },
    {
      "question": "Explain why gamma rays are used in medical sterilization.",
      "question_type": "objective",
      "topic": "Nuclear Physics",
      "subtopic": "Radiation Applications",
      "options": [
        "They are low energy",
        "They penetrate materials deeply",
        "They are easily absorbed",
        "They are non-ionizing"
      ],
      "correct_answers": ["They penetrate materials deeply"],
      "explanation": "Gamma rays are used in sterilization due to their high penetration, killing bacteria by ionizing cells. They are high-energy and ionizing, unlike other options.",
      "hint": "Think about radiation that passes through equipment.",
      "difficulty": "Hard",
      "marks": 1,
      "media_url": "https://example.com/images/gamma_sterilization.jpg",
      "media_type": "image",
      "keywords": ["Gamma Rays", "Sterilization", "Nuclear Physics"],
      "learning_objectives": ["Explain radiation applications"],
      "estimated_time": "3 minutes",
      "source_reference": "WAEC Past Questions 2022",
      "ai_feedback": "This DOK 3 question requires explaining radiation use."
    },
    {
      "question": "Which of the following is the unit of magnetic flux?",
      "question_type": "objective",
      "topic": "Electromagnetism",
      "subtopic": "Magnetic Fields",
      "options": [
        "Tesla",
        "Weber",
        "Henry",
        "Gauss"
      ],
      "correct_answers": ["Weber"],
      "explanation": "The SI unit of magnetic flux is the Weber, measuring magnetic field through a surface. Other units measure different properties.",
      "hint": "Think about magnetic field strength over an area.",
      "difficulty": "Easy",
      "marks": 1,
      "media_url": "https://example.com/images/magnetic_flux.jpg",
      "media_type": "image",
      "keywords": ["Magnetic Flux", "Weber", "Electromagnetism"],
      "learning_objectives": ["Identify SI units for magnetic quantities"],
      "estimated_time": "1 minute",
      "source_reference": "WAEC Past Questions 2021",
      "ai_feedback": "This DOK 1 question tests recall of magnetic units."
    },
    {
      "question": "A 10 kg object is on a surface with a frictional force of 20 N. Calculate the minimum force needed to move it.",
      "question_type": "objective",
      "topic": "Mechanics",
      "subtopic": "Friction",
      "options": [
        "20 N",
        "10 N",
        "30 N",
        "100 N"
      ],
      "correct_answers": ["20 N"],
      "explanation": "The minimum force to overcome friction equals the frictional force, 20 N. Weight (mg) is irrelevant unless motion is vertical.",
      "hint": "Consider the force opposing motion.",
      "difficulty": "Medium",
      "marks": 1,
      "media_url": "https://example.com/images/friction_diagram.jpg",
      "media_type": "image",
      "keywords": ["Friction", "Force", "Mechanics"],
      "learning_objectives": ["Calculate forces involving friction"],
      "estimated_time": "2 minutes",
      "source_reference": "WAEC Past Questions 2020",
      "ai_feedback": "This DOK 2 question requires applying friction concepts."
    },
    {
      "question": "Design a method to determine the refractive index of a glass block.",
      "question_type": "objective",
      "topic": "Optics",
      "subtopic": "Refraction",
      "options": [
        "Measure light intensity",
        "Measure angles of incidence and refraction",
        "Measure glass density",
        "Measure light speed directly"
      ],
      "correct_answers": ["Measure angles of incidence and refraction"],
      "explanation": "To find the refractive index, measure the angles of incidence and refraction using Snell’s Law (n = sin i / sin r). Other methods are not suitable.",
      "hint": "Think about Snell’s Law.",
      "difficulty": "Hard",
      "marks": 1,
      "media_url": "https://example.com/images/refraction_experiment.jpg",
      "media_type": "image",
      "keywords": ["Refractive Index", "Snell’s Law", "Optics"],
      "learning_objectives": ["Design experiments for refraction"],
      "estimated_time": "3 minutes",
      "source_reference": "WAEC Past Questions 2021",
      "ai_feedback": "This DOK 4 question requires designing an experiment."
    },
    {
      "question": "A transformer steps up voltage from 220 V to 11,000 V. Calculate the turns ratio.",
      "question_type": "objective",
      "topic": "Electromagnetism",
      "subtopic": "Transformers",
      "options": [
        "50:1",
        "1:50",
        "220:1",
        "1:220"
      ],
      "correct_answers": ["50:1"],
      "explanation": "Turns ratio = V₂/V₁ = 11,000 V / 220 V = 50:1 (secondary to primary). Other ratios are incorrect.",
      "hint": "Use the transformer voltage ratio.",
      "difficulty": "Medium",
      "marks": 1,
      "media_url": "https://example.com/images/transformer_diagram.png",
      "media_type": "image",
      "keywords": ["Transformer", "Turns Ratio", "Electromagnetism"],
      "learning_objectives": ["Calculate transformer turns ratio"],
      "estimated_time": "2 minutes",
      "source_reference": "WAEC Past Questions 2022",
      "ai_feedback": "This DOK 2 question requires applying transformer principles."
    }
  ],
  "questionCount": 35,
  "total_marks": 35,
  "duration": "1 hours",
  "file_url": "https://example.com/files/wassce_physics_2024_revised.pdf",
  "isPublic": true,
  "tags": ["Mechanics", "Thermal Physics", "Electricity", "Optics", "Electromagnetism", "Nuclear Physics", "Waves", "Energy"],
  "difficulty": "Medium",
  "language": "English",
  "status": "Published",
  "instructions": "Answer all questions by selecting the correct option. Ensure your answers are clear and complete."
}
]